### ISSUE TITLE
Create Amazon EC2 Image

### ISSUE THREAD

**Issue by eldhomathulla** [airavata-courses/TeamAlphaFall#15]
Create Amazon EC2 image with following packages:
JRE 8 (java 8)
Python 3.4
Postgresql 9.3

**Comment by Ameya05** [comment]
Created Amazon EC2 image [TeamOmniJava8andPostgreSQL93] with-
JDK 8
Postgresql 9.3

---

Planning on downgrading Python scripts to 2.7.x version which is installed on Amazon EC2 instances by default.
