### ISSUE TITLE
Merging UI with Orchestration Engine

### ISSUE THREAD

**Issue by eldhomathulla** [airavata-courses/TeamAlphaFall#30]
Merging UI with orchestration engine

**Comment by Ameya05** [comment]
UI components were moved from feature-UI branch to feature-orchestrationengine successfully.
UI is now bundled along with the orchestration engine.
Link to UI Components -> https://github.com/airavata-courses/TeamOmni/tree/feature-orchestrationengine/OrchestrationEngineService/src/main/webapp
